/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firstsw;

/**
 *
 * @author GD
 */
public class first extends javax.swing.JFrame 
{

    /**
     * Creates new form first
     */
    public first() 
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagepanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bright_label = new javax.swing.JLabel();
        filter_label = new javax.swing.JLabel();
        translabel = new javax.swing.JLabel();
        bright_slider = new javax.swing.JSlider();
        bright_setbut = new javax.swing.JButton();
        filter_blur = new javax.swing.JButton();
        filter_black = new javax.swing.JButton();
        filter_sepia = new javax.swing.JButton();
        filter_rev = new javax.swing.JButton();
        filter_sharp = new javax.swing.JButton();
        rotalabel = new javax.swing.JLabel();
        cw_radio = new javax.swing.JRadioButton();
        ccw_radio = new javax.swing.JRadioButton();
        user_radio = new javax.swing.JRadioButton();
        rotauser_text = new javax.swing.JTextField();
        rota_setbut = new javax.swing.JButton();
        revlabel = new javax.swing.JLabel();
        rev_tbbut = new javax.swing.JButton();
        rev_rlbut = new javax.swing.JButton();
        size_label = new javax.swing.JLabel();
        size_xlabel = new javax.swing.JLabel();
        size_xtext = new javax.swing.JTextField();
        size_ylabel = new javax.swing.JLabel();
        size_ytext = new javax.swing.JTextField();
        size_setbut = new javax.swing.JButton();
        form_label = new javax.swing.JLabel();
        form_jpegradio = new javax.swing.JRadioButton();
        form_jpgradio = new javax.swing.JRadioButton();
        form_pngradio = new javax.swing.JRadioButton();
        form_bmpradio = new javax.swing.JRadioButton();
        form_jifradio = new javax.swing.JRadioButton();
        form_setbut = new javax.swing.JButton();
        reset_but = new javax.swing.JButton();
        cut_label = new javax.swing.JLabel();
        cut_but = new javax.swing.JButton();
        bright_value = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        deco_label = new javax.swing.JLabel();
        fradeco_label = new javax.swing.JLabel();
        comlabel = new javax.swing.JLabel();
        com_iamgebut = new javax.swing.JButton();
        fradeco_oneradio = new javax.swing.JRadioButton();
        fradeco_tworadio = new javax.swing.JRadioButton();
        fradeco_thradio = new javax.swing.JRadioButton();
        fradeco_fourradio = new javax.swing.JRadioButton();
        fradeco_setbut = new javax.swing.JButton();
        logolabel = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        menuedit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagepanel.setBackground(new java.awt.Color(102, 102, 102));
        imagepanel.setPreferredSize(new java.awt.Dimension(512, 0));

        javax.swing.GroupLayout imagepanelLayout = new javax.swing.GroupLayout(imagepanel);
        imagepanel.setLayout(imagepanelLayout);
        imagepanelLayout.setHorizontalGroup(
            imagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagepanelLayout.setVerticalGroup(
            imagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        bright_label.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        bright_label.setText("밝기 조절");

        filter_label.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        filter_label.setText("필터 효과");

        translabel.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        translabel.setText("사진 변형");

        bright_slider.setBackground(new java.awt.Color(255, 255, 255));
        bright_slider.setInheritsPopupMenu(true);
        bright_slider.setInverted(true);

        bright_setbut.setText("적용");
        bright_setbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bright_setbutActionPerformed(evt);
            }
        });

        filter_blur.setText("흐림");
        filter_blur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_blurActionPerformed(evt);
            }
        });

        filter_black.setText("흑백");
        filter_black.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_blackActionPerformed(evt);
            }
        });

        filter_sepia.setText("세피아");

        filter_rev.setText("반전");

        filter_sharp.setText("선명");

        rotalabel.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        rotalabel.setText("회전");

        cw_radio.setBackground(new java.awt.Color(255, 255, 255));
        cw_radio.setText("시계 방향");
        cw_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cw_radioActionPerformed(evt);
            }
        });

        ccw_radio.setBackground(new java.awt.Color(255, 255, 255));
        ccw_radio.setText("반시계 방향");

        user_radio.setBackground(new java.awt.Color(255, 255, 255));
        user_radio.setText("사용자 지정 : ");

        rotauser_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotauser_textActionPerformed(evt);
            }
        });

        rota_setbut.setText("적용");

        revlabel.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        revlabel.setText("반전");

        rev_tbbut.setText("상하 반전");

        rev_rlbut.setText("좌우 반전");

        size_label.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        size_label.setText("크기 조절");

        size_xlabel.setText("가로 :");

        size_xtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size_xtextActionPerformed(evt);
            }
        });

        size_ylabel.setText("세로 :");

        size_ytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size_ytextActionPerformed(evt);
            }
        });

        size_setbut.setText("적용");

        form_label.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        form_label.setText("포멧 변경");

        form_jpegradio.setBackground(new java.awt.Color(255, 255, 255));
        form_jpegradio.setText(" JPEG");
        form_jpegradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_jpegradioActionPerformed(evt);
            }
        });

        form_jpgradio.setBackground(new java.awt.Color(255, 255, 255));
        form_jpgradio.setText(" JPG");

        form_pngradio.setBackground(new java.awt.Color(255, 255, 255));
        form_pngradio.setText("PNG");

        form_bmpradio.setBackground(new java.awt.Color(255, 255, 255));
        form_bmpradio.setText("BMP");

        form_jifradio.setBackground(new java.awt.Color(255, 255, 255));
        form_jifradio.setText("JIF");
        form_jifradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_jifradioActionPerformed(evt);
            }
        });

        form_setbut.setText("변경");
        form_setbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_setbutActionPerformed(evt);
            }
        });

        reset_but.setText("원본 되돌리기");
        reset_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_butActionPerformed(evt);
            }
        });

        cut_label.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        cut_label.setText("자르기");

        cut_but.setText("자르기");

        bright_value.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rev_tbbut, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(rev_rlbut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cw_radio)
                                                .addGap(42, 42, 42))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(user_radio)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ccw_radio)
                                            .addComponent(rotauser_text, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(rotalabel)
                                    .addComponent(revlabel)
                                    .addComponent(cut_label)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(form_pngradio)
                                            .addComponent(form_jpegradio))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(form_jpgradio)
                                            .addComponent(form_jifradio))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(form_bmpradio)
                                            .addComponent(form_setbut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(size_label)
                                    .addComponent(form_label)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cut_but, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(size_xlabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(size_xtext, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(size_ylabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(size_ytext, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(47, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(filter_black, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(filter_sharp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(filter_rev, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(filter_blur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(filter_label, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(translabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bright_label, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(bright_slider, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bright_value, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bright_setbut))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(236, 236, 236)
                                    .addComponent(filter_sepia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rota_setbut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(size_setbut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(reset_but)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bright_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bright_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bright_setbut)
                        .addComponent(bright_value)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filter_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter_black)
                    .addComponent(filter_blur)
                    .addComponent(filter_sepia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filter_sharp)
                    .addComponent(filter_rev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(translabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotalabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cw_radio)
                    .addComponent(ccw_radio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_radio)
                    .addComponent(rotauser_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rota_setbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(revlabel)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rev_tbbut)
                    .addComponent(rev_rlbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(size_label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size_xlabel)
                    .addComponent(size_xtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size_ylabel)
                    .addComponent(size_ytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size_setbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(form_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(form_jpegradio)
                    .addComponent(form_jpgradio)
                    .addComponent(form_bmpradio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(form_jifradio)
                        .addComponent(form_setbut))
                    .addComponent(form_pngradio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cut_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cut_but)
                .addGap(7, 7, 7)
                .addComponent(reset_but)
                .addGap(49, 49, 49))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {filter_black, filter_blur, filter_rev, filter_sepia});

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        deco_label.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        deco_label.setText("꾸미기");

        fradeco_label.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        fradeco_label.setText("액자 꾸미기");

        comlabel.setFont(new java.awt.Font("맑은 고딕", 1, 12)); // NOI18N
        comlabel.setText("사진 합치기");

        com_iamgebut.setText("사진 불러오기");
        com_iamgebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_iamgebutActionPerformed(evt);
            }
        });

        fradeco_oneradio.setBackground(new java.awt.Color(255, 255, 255));
        fradeco_oneradio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        fradeco_oneradio.setText("액자1");

        fradeco_tworadio.setBackground(new java.awt.Color(255, 255, 255));
        fradeco_tworadio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        fradeco_tworadio.setText("액자2");

        fradeco_thradio.setBackground(new java.awt.Color(255, 255, 255));
        fradeco_thradio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        fradeco_thradio.setText("액자3");

        fradeco_fourradio.setBackground(new java.awt.Color(255, 255, 255));
        fradeco_fourradio.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        fradeco_fourradio.setText("액자4");

        fradeco_setbut.setText("적용");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deco_label)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comlabel)
                                    .addComponent(fradeco_label)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(fradeco_oneradio)))
                        .addGap(31, 31, 31)
                        .addComponent(fradeco_tworadio)
                        .addGap(31, 31, 31)
                        .addComponent(fradeco_thradio)
                        .addGap(31, 31, 31)
                        .addComponent(fradeco_fourradio)
                        .addGap(31, 31, 31)
                        .addComponent(fradeco_setbut, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(com_iamgebut)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deco_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fradeco_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fradeco_tworadio)
                    .addComponent(fradeco_oneradio)
                    .addComponent(fradeco_thradio)
                    .addComponent(fradeco_fourradio)
                    .addComponent(fradeco_setbut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(com_iamgebut)
                .addGap(14, 14, 14))
        );

        logolabel.setBackground(new java.awt.Color(51, 153, 255));
        logolabel.setText("로고");

        menufile.setText("File");
        menu.add(menufile);

        menuedit.setText("Edit");
        menu.add(menuedit);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void size_ytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size_ytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size_ytextActionPerformed

    private void size_xtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size_xtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size_xtextActionPerformed

    private void rotauser_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotauser_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotauser_textActionPerformed

    private void cw_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cw_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cw_radioActionPerformed

    private void filter_blackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_blackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_blackActionPerformed

    private void filter_blurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_blurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_blurActionPerformed

    private void bright_setbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bright_setbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bright_setbutActionPerformed

    private void form_jpegradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_jpegradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_jpegradioActionPerformed

    private void form_jifradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_jifradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_jifradioActionPerformed

    private void form_setbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_setbutActionPerformed
        // TODO add your handling code here:
        System.out.println("HI");
    }//GEN-LAST:event_form_setbutActionPerformed

    private void reset_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reset_butActionPerformed

    private void com_iamgebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_iamgebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_iamgebutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new first().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bright_label;
    private javax.swing.JButton bright_setbut;
    private javax.swing.JSlider bright_slider;
    private javax.swing.JLabel bright_value;
    private javax.swing.JRadioButton ccw_radio;
    private javax.swing.JButton com_iamgebut;
    private javax.swing.JLabel comlabel;
    private javax.swing.JButton cut_but;
    private javax.swing.JLabel cut_label;
    private javax.swing.JRadioButton cw_radio;
    private javax.swing.JLabel deco_label;
    private javax.swing.JButton filter_black;
    private javax.swing.JButton filter_blur;
    private javax.swing.JLabel filter_label;
    private javax.swing.JButton filter_rev;
    private javax.swing.JButton filter_sepia;
    private javax.swing.JButton filter_sharp;
    private javax.swing.JRadioButton form_bmpradio;
    private javax.swing.JRadioButton form_jifradio;
    private javax.swing.JRadioButton form_jpegradio;
    private javax.swing.JRadioButton form_jpgradio;
    private javax.swing.JLabel form_label;
    private javax.swing.JRadioButton form_pngradio;
    private javax.swing.JButton form_setbut;
    private javax.swing.JRadioButton fradeco_fourradio;
    private javax.swing.JLabel fradeco_label;
    private javax.swing.JRadioButton fradeco_oneradio;
    private javax.swing.JButton fradeco_setbut;
    private javax.swing.JRadioButton fradeco_thradio;
    private javax.swing.JRadioButton fradeco_tworadio;
    private javax.swing.JPanel imagepanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logolabel;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuedit;
    private javax.swing.JMenu menufile;
    private javax.swing.JButton reset_but;
    private javax.swing.JButton rev_rlbut;
    private javax.swing.JButton rev_tbbut;
    private javax.swing.JLabel revlabel;
    private javax.swing.JButton rota_setbut;
    private javax.swing.JLabel rotalabel;
    private javax.swing.JTextField rotauser_text;
    private javax.swing.JLabel size_label;
    private javax.swing.JButton size_setbut;
    private javax.swing.JLabel size_xlabel;
    private javax.swing.JTextField size_xtext;
    private javax.swing.JLabel size_ylabel;
    private javax.swing.JTextField size_ytext;
    private javax.swing.JLabel translabel;
    private javax.swing.JRadioButton user_radio;
    // End of variables declaration//GEN-END:variables
}
